# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  email_provider_username: <%= ENV["MAILGUN_SMTP_LOGIN"] %>
  email_provider_password: <%= ENV["MAILGUN_SMTP_PASSWORD"] %>
  domain_name: blocmarks.dev
  secret_key_base: 47b5c14c1c5526d890e1b288df632123e5b03a6cc72998ec540ba90cbfbec62c385247fd704e9de11783a8bdc7c9f7c7875a68abe8a0374866e0f2bab8de54e6

test:
  secret_key_base: 2b8c21c764c80f316201b07df8b4ea2480120be9ef8a02e8bf4bd8824d1a335dea556dcb0be76054a0eaa0f41ae5181a8412f1b289638228c3a61c86445f0040

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
